<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Run All test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>606c6919-c19a-4362-a73f-d16a97d24eaa</testSuiteGuid>
   <testCaseLink>
      <guid>0268e1dc-79e9-4a31-a9ce-f960720c885c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Database/Reset Password</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ca20d927-6c89-4701-859e-a0d09e747e77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register/Parent register successful</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>52136c04-afa9-4029-a888-06552e1593fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registation/Add New Player</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f2d6c67-9bfb-43e2-a81c-1576d85c6761</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e57de71-cfe7-4aed-ad4c-c95adcb5b7b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83296224-8142-431f-b0cf-780c3122d5d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2994e8-a7c5-42d0-8d64-f0a02b17acb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ffaf28-dc6c-4cef-ad9a-cd561eee653e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7af6eb-2f08-4339-9b74-2533c88c1ac2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>754d88c9-291b-43fe-8e8b-d92b3a06f9ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e64cde-b17c-4ded-bce3-3614c1efe0e2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
